export const SAVE_NEW_LIST = 'list-creator/SAVE_NEW_LIST';

export const REQUEST_SHOPPING_LISTS = 'list-creator/REQUEST_SHOPPING_LISTS';
export const RECEIVE_SHOPPING_LISTS = 'list-creator/RECEIVE_SHOPPING_LISTS';

export const UPDATE_SHOPPING_LISTS_BEGIN = 'list-creator/UPDATE_SHOPPING_LISTS_BEGIN';
export const UPDATE_SHOPPING_LISTS_END = 'list-creator/UPDATE_SHOPPING_LISTS_END';
