export const MARK_PRODUCT_AS_PURCHASED = 'MARK_PRODUCT_AS_PURCHASED';
export const SHOW_PRODUCT_PRICES_TREND= 'SHOW_PRODUCT_PRICES_TREND'
export const REQUEST_PRICES = 'REQUEST_PRICES'
export const RECEIVE_PRICES = 'RECEIVE_PRICES'