export const TOGGLE_FAVORITE_FILTER = 'filters/TOGGLE_FAVORITE_FILTER';
export const SET_CATEGORY_FILTER = 'filters/SET_CATEGORY_FILTER';
export const REMOVE_CATEGORY_FILTERS = 'filters/REMOVE_CATEGORY_FILTERS'